FROM python:3.11-slim-bookworm

RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    && rm -rf /var/lib/apt/lists/*

RUN pip install feast==0.34.0 redis==5.0.1

WORKDIR /app

COPY pipelines/data_pipeline/transformation/feature_store.py /app/
COPY pipelines/data_pipeline/transformation/feast_config/ /app/feast_config/

ENV REDIS_HOST=redis \
    REDIS_PORT=6379

CMD ["feast", "serve", "-h", "0.0.0.0", "-p", "6566"]